### ISSUE TITLE
Missing sequence

### ISSUE THREAD

**Issue by nkahoang** [adobe/commerce-cif-magento#68]
### Expected Behaviour

On this line

https://github.com/adobe/commerce-cif-magento/blob/master/customer-deployment/serverless.yml#L274

There is a reference to `- ${self:custom.products-actions}/getProductBySlugService` however that service looks like it's unavailable.

This is the error that I get

  Serverless Error ---------------------------------------

  Failed to deploy function (magento/getProductBySlug) due to error: PUT https://adobeioruntime.net/api/v1/namespaces/{NAME_SPACE}/actions/magento/getProductBySlug?overwrite=true Returned HTTP 400 (Bad Request) --> "Sequence component does not exist."

**Comment by herzog31** [comment]
The `getProductBySlugService` service is defined here: https://github.com/adobe/commerce-cif-magento/blob/master/src/products/serverless.yml#L31.

**Comment by mhaack** [comment]
@nkahoang I released and deployed the missing actions today, which fixes this issue.
